# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4f7a86895d0e8009c87a61b861a6d717c604b8169e0e9af6d560e5818643542b7fada00463cbd72e5ddd0659ab27b4eac7f866989bb4c3f855210c42f457889

test:
  secret_key_base: 5744499f05757b4b26a1968aa1fdfa5adcd3d77d08cbe97882eea43ce7a6670cdcf49c96659193c5441bcf41e48dbfa60dd38b0db1a58546cd08f7af13501671

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
